### ISSUE TITLE
the transformer head number

### ISSUE THREAD

**Issue by 863689877** [zacjiang/GMA#1]
Thank you for your concise and efficient work!
I would like to ask a question about the impact of the transformer head's number. I found no ablation experiments for this variable in the paper you published, and you set it to 1 in your code. 
May I ask if you have conducted relevant experiments on this variable, and whether the performance will be improved if the number is increased?

**Comment by zacjiang** [comment]
Thanks for your interest. 
I didn't observe improved performance with larger head numbers and gpu memory also goes up pretty quickly with larger head numbers. So in the end I just set it to 1.

**Comment by 863689877** [comment]
I see, and thank you for your reply
