### ISSUE TITLE
How to handle subtitle with large motion?

### ISSUE THREAD

**Issue by leiwen83** [zacjiang/GMA#10]
Hi,

I wonder to know whether GMA could handle the case that subtitle accompany with large motion which is common in the movie?
Would the subtitle be kept well in the interpolation result?

**Comment by zacjiang** [comment]
Hi, did you mean estimating the motion of the subtitle?

**Comment by leiwen83** [comment]
No. Subtitle is always still, but meanwhile the action move in the video could be large, which may cause warp stage take wrong pixel from the subtitle area to the video, or verse vice. We see a lot in previous works, like DAIN, cannot handle this case well. Just curious whether GMA could handle it.

**Comment by zacjiang** [comment]
My guess is that it won't be able to handle it, but you're welcome to try.

**Comment by zacjiang** [comment]
I just came across this paper "Video Frame Interpolation via Deformable Separable Convolution", in Figure 5, they seem to be able to reconstruct the subtitle well. Not sure how large the motion is though.
