### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by forbyme** [zacjiang/GMA#11]
Hi!  great work!  When I tested sintel-test-final dataset and created a create_sintel_submission,  It happened" IndexError: index 0 is out of bounds for axis 0 with size 0" on a pair of images, why?

**Comment by zacjiang** [comment]
I didn't come across this problem before. Can you provide more details?

**Comment by forbyme** [comment]
I have solved it, thanks!
