### ISSUE TITLE
Why don't you use "attention=self.att(fmp1)", but use "attention=self.att(inp)"

### ISSUE THREAD

**Issue by forbyme** [zacjiang/GMA#12]
Hi, good work ! I have a question .Why don't you use "attention=self.att(fmp1)", but use "attention=self.att(inp)"

**Comment by zacjiang** [comment]
If you read the paper, fmap1 refers to the matching features and inp refers to the context features. The attention matrix is computed on the context features to model self-similarities.

**Comment by forbyme** [comment]
Thank you for your explanation, could you explain the difference between the fmp1 and inp in detail?  I think the feature information in the fmap1 is more rich and detailed, it would be better to model self-similarities. Have you done relevant ablation experiments?

**Comment by zacjiang** [comment]
Yep, sure. If you look at Figure 3 in the paper, there are two network blocks: feature network and context network. The feature network is used to extract matching features that are used for computing the correlation volume, which is fmap1. The context network is used to extract context features which are used for refinement as well as modelling self-similarities. Noted that they can share weights but I didn't do that, following the original design in RAFT. I didn't run ablation experiments on it.

**Comment by forbyme** [comment]
Thank you very much for your explanation. It was a very good job!

**Comment by forbyme** [comment]
Thank you very much for your explanation. It was a very good job!
