### ISSUE TITLE
Attention Map Visualization

### ISSUE THREAD

**Issue by Bayrambai** [zacjiang/GMA#13]
Thanks for making your source code public.
Could you please share your code for visualizing the attention map in Figure 6 or guide me on how to obtain it?

**Comment by zacjiang** [comment]
Yep, here you go. 
```
coordinates = [(60, 40)]
for i, (x, y) in enumerate(coordinates):
    att_map = att[0, 0, y, x].cpu().numpy()
    plt.figure()
    plt.imshow(att_map, cmap='hot')
    plt.text(x - 8, y + 1, f'{i+1}', color='w', size=15)
    plt.scatter(x, y, s=120, color='w', marker='o')
    plt.axis('off')
    plt.savefig(os.path.join(flow_dir, f'x_{i+1}_{x}_y_{y}_att_map.png'), bbox_inches='tight', pad_inches=0)
    plt.close()
```

**Comment by Bayrambai** [comment]
Thanks, closing

**Comment by forbyme** [comment]
> Yep, here you go.
> 
> ```
> coordinates = [(60, 40)]
> for i, (x, y) in enumerate(coordinates):
>     att_map = att[0, 0, y, x].cpu().numpy()
>     plt.figure()
>     plt.imshow(att_map, cmap='hot')
>     plt.text(x - 8, y + 1, f'{i+1}', color='w', size=15)
>     plt.scatter(x, y, s=120, color='w', marker='o')
>     plt.axis('off')
>     plt.savefig(os.path.join(flow_dir, f'x_{i+1}_{x}_y_{y}_att_map.png'), bbox_inches='tight', pad_inches=0)
>     plt.close()
> ```

How do I add it to the model
