### ISSUE TITLE
Two-view results on Sintel

### ISSUE THREAD

**Issue by xiaofeng94** [zacjiang/GMA#15]
Hi @zacjiang 

Would you like to release the 2-view results on Sintel as RAFT, i.e. the results without warm-start?

**Comment by zacjiang** [comment]
You can generate that yourself with the provided checkpoints.

**Comment by xiaofeng94** [comment]
Thanks for your quick response. 
I'd like to know the quantitative results for comparison. Can I generate the 2-view results and submit them to the Sintel test server.

**Comment by zacjiang** [comment]
Yes, that'll be fine, but please keep it private.
