### ISSUE TITLE
Cannot find file named 'things_val_test_set.txt'

### ISSUE THREAD

**Issue by 863689877** [zacjiang/GMA#8]
Hi, file named 'things_val_test_set.txt' cannot be found in in core/datasets.py, which leads to failure when validate flyingthings3d dataset. 
Please provide this file, and explain the source of that. Thanks.

**Comment by zacjiang** [comment]
I have added the file. It is just to select a subset of the TEST set in FlyingThings3D, where I select 1 in every 10 frames.
